apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eck
  namespace: argocd
spec:
  project: default
  source:
    repoURL:  https://github.com/sosotechnologies/dev-master.git
    targetRevision: HEAD
    path: non-helm/eck
  destination:
    namespace: eck
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true