apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube
  namespace: argocd
spec:
  destination:
    namespace: sonarqube
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: helm/sonarqube
    # kustomize:
    #   version: v4.5.7
    repoURL:  https://github.com/sosotechnologies/dev-master.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true